# Aviumui Flags
AVIUM_VERSION_APPEND_TIME_OF_DAY := true
AUM_MAINTAINER := スリーラジ and キムチ
AVIUM_SETTINGS_SOC_MODEL_NAME := SM6250
AVIUM_SETTINGS_DEVICE_CODENAME := Miatoll
WITH_GMS := true
TARGET_USES_GSANS := true
AVIUM_FORCE_SET_FAKE_PROP := true
TARGET_FORCE_ENABLE_BLUR := true
AVIUM_FORCE_SET_FAKE_PROP := true
